(display (append (new-object "java.lang.String" "hello") "world"))
(display #\newline)
(display (append (new-object "java.lang.String" "hello") "world"))
(display #\newline)
(if #f (display "yes") (display "no"))
