(define ln ( lambda (x) ( if (= x 1 ) 1 ( * x ( ln ( - x 1 ))))))
(define ks (lambda (x n) ( if (= n 0 ) 1 ( * x ( ks x ( - n  1 ))))))
(define tim (lambda (x n ) ( / (ks x n ) (ln n))))
(define kr (lambda (x) (= ( % x 2 ) 0 ) ))
(define md (lambda (x n) (tim x ( - ( * 2 n ) 1 ))))
(define xx (lambda (x n ) (if (kr n ) ( - 0 (md x n )) (md x n ))))
(define sin (lambda (x n) (if ( = n 0) 0 (+ (xx x n) (sin x ( - n 1 ))))))
(display (sin 3.14159 10))
